services:
  s3manager:
    image: cloudlena/s3manager
    container_name: s3manager
    restart: always 
    ports:
      - "172.17.0.1:59094:8080"
    environment:
      - USE_SSL=false
      - ENDPOINT=garagehq:3900
      - ACCESS_KEY_ID=
      - SECRET_ACCESS_KEY=
    depends_on:
      - garagehq

  garagehq:
    image: dxflrs/garage:v0.9.3
    container_name: garagehq
    restart: always 
    environment:
      - RUST_LOG=garage=info
      - GARAGE_ADMIN_TOKEN="${DB_ADMIN_PASS}"
      - GARAGE_METRICS_TOKEN="${DB_ADMIN_PASS}"
      - GARAGE_RPC_SECRET="${RPC_SECRET:-4cdefce7d9b1cfd5f2f6674d2349efa38684bc69039e3cf6cafb65d68e26c5f4}" # openssl rand -hex 32
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
      - "3904:3904"
    volumes:
      - "./config/garage.toml:/etc/garage.toml" 
      - "/var/lib/srv/$USER/docker/dxflrs/garage/latest/rootfs/data/garage:/var/lib/garage/data"
      - "/var/lib/srv/$USER/docker/dxflrs/garage/latest/rootfs/config/garage:/var/lib/garage/meta"  
